export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const FEATURED_PRODUCTS_REQUEST = 'FEATURED_PRODUCTS_REQUEST';
export const FEATURED_PRODUCTS_SUCCESS = 'FEATURED_PRODUCTS_SUCCESS';
export const FEATURED_PRODUCTS_FAIL = 'FEATURED_PRODUCTS_FAIL';

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST';
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET';
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCTS_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCTS_SUCCESS';
export const ADD_PRODUCT_RESET = 'ADD_PRODUCTS_RESET';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCTS_FAIL';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCTS_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCTS_SUCCESS';
export const UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCTS_RESET';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCTS_FAIL';

export const USER_PRODUCTS_REQUEST = 'USER_PRODUCTS_REQUEST';
export const USER_PRODUCTS_SUCCESS = 'USER_PRODUCTS_SUCCESS';
export const USER_PRODUCTS_FAIL = 'USER_PRODUCTS_FAIL';

export const GET_PRODUCT_REVENUE_REQUEST = "GET_PRODUCT_REVENUE_REQUEST";
export const GET_PRODUCT_REVENUE_SUCCESS = "GET_PRODUCT_REVENUE_SUCCESS";
export const GET_PRODUCT_REVENUE_FAIL = "GET_PRODUCT_REVENUE_FAIL";
